/*
 * AlmaRM Model - Java represenation of the model AlmaRM is built on.
 * Copyright (C) 2018  ALMA MATER STUDIORUM - Università di Bologna
 *
 * This file is part of AlmaRM Model.
 *
 * AlmaRM Model is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * AlmaRM Model is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with AlmaRM Model.  If not, see <https://www.gnu.org/licenses/>.
 */
package it.unibo.almarm.model.esterni;

import it.unibo.almarm.webapp.mvc.Lingua;

import org.regola.util.Ognl;

// Generated 24-gen-2008 9.04.39 by Hibernate Tools 3.2.0.CR1

/**
 * TipoEntitaEsterna generated by hbm2java
 */
public class TipoEntitaEsterna implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	public static final Long ID_TIPO_ENTE_PUBBLICO = 1L;
	public static final Long ID_TIPO_SOCIETA_DI_CAPITALI = 2L;
	public static final Long ID_TIPO_ASSOCIAZIONE_FONDAZIONE = 4L;
	public static final Long ID_TIPO_UNIVERSITA_E_IST_SUPERORI = 6L;
	
	private Long id;
	private String descrizione;
	private String descrizioneIng;


	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public String getDescrizioneIng() {
		return descrizioneIng;
	}

	public void setDescrizioneIng(String descrizioneIng) {
		this.descrizioneIng = descrizioneIng;
	}
	
	public String getLocaleDescrizione() {
		Object propertyValue = Ognl.getValue("descrizione"+Lingua.getSuffissoNomeCampoDiModello(), this);
		if (propertyValue != null)
		{
			String val=(String)propertyValue;
			return val;
		}
		return "";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((descrizione == null) ? 0 : descrizione.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof TipoEntitaEsterna))
			return false;
		final TipoEntitaEsterna other = (TipoEntitaEsterna) obj;
		if (descrizione == null) {
			if (other.getDescrizione() != null)
				return false;
		} else if (!descrizione.equals(other.getDescrizione()))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return id.toString();
	}

	public boolean isEntePubblico() {
		return this.id.equals(ID_TIPO_ENTE_PUBBLICO);
	}

	public boolean isAssociazioneOFondazione() {
		return this.id.equals(ID_TIPO_ASSOCIAZIONE_FONDAZIONE);
	}
}
