/*
 * AlmaRM Model - Java represenation of the model AlmaRM is built on.
 * Copyright (C) 2018  ALMA MATER STUDIORUM - Università di Bologna
 *
 * This file is part of AlmaRM Model.
 *
 * AlmaRM Model is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * AlmaRM Model is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with AlmaRM Model.  If not, see <https://www.gnu.org/licenses/>.
 */
package it.unibo.almarm.model.luoghi;

// Generated 18-gen-2008 12.52.20 by Hibernate Tools 3.2.0.CR1

/**
 * Localita generated by hbm2java
 */
public class Localita implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Long id;
	private Territorio territorio;
	private String codMinisteriale;
	private String localita;
	private String localitaOrig;
	private Long statoCodifica;
	private Long nascita;
	private Long postale;
	private Long residenza;
	
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Territorio getTerritorio() {
		return this.territorio;
	}

	public void setTerritorio(Territorio territorio) {
		this.territorio = territorio;
	}

	public String getCodMinisteriale() {
		return this.codMinisteriale;
	}

	public void setCodMinisteriale(String codMinisteriale) {
		this.codMinisteriale = codMinisteriale;
	}

	public String getLocalita() {
		return this.localita;
	}

	public void setLocalita(String localita) {
		this.localita = localita;
	}

	public String getLocalitaOrig() {
		return this.localitaOrig;
	}

	public void setLocalitaOrig(String localitaOrig) {
		this.localitaOrig = localitaOrig;
	}

	public Long getStatoCodifica() {
		return this.statoCodifica;
	}

	public void setStatoCodifica(Long statoCodifica) {
		this.statoCodifica = statoCodifica;
	}

	public Long getNascita() {
		return this.nascita;
	}

	public void setNascita(Long nascita) {
		this.nascita = nascita;
	}

	public Long getPostale() {
		return this.postale;
	}

	public void setPostale(Long postale) {
		this.postale = postale;
	}

	public Long getResidenza() {
		return this.residenza;
	}

	public void setResidenza(Long residenza) {
		this.residenza = residenza;
	}


	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((localita == null) ? 0 : localita.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof Localita))
			return false;
		final Localita other = (Localita) obj;
		if (localita == null) {
			if (other.getLocalita() != null)
				return false;
		} else if (!localita.equals(other.getLocalita()))
			return false;
		return true;
	}

	
	
}
