/*
 * AlmaRM Model - Java represenation of the model AlmaRM is built on.
 * Copyright (C) 2018  ALMA MATER STUDIORUM - Università di Bologna
 *
 * This file is part of AlmaRM Model.
 *
 * AlmaRM Model is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * AlmaRM Model is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with AlmaRM Model.  If not, see <https://www.gnu.org/licenses/>.
 */
package it.unibo.almarm.model.luoghi;

// Generated 18-gen-2008 12.52.20 by Hibernate Tools 3.2.0.CR1


/**
 * Territorio generated by hbm2java
 */
public class Territorio implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Long id;
	private Regione regione;
	private String territorio;
	private String territorioOrig;
	private String codiceIso;
	private Long statoCodifica;

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Regione getRegione() {
		return this.regione;
	}

	public void setRegione(Regione regione) {
		this.regione = regione;
	}
	
	public String getTerritorio() {
		return this.territorio;
	}

	public void setTerritorio(String territorio) {
		this.territorio = territorio;
	}

	public String getTerritorioOrig() {
		return this.territorioOrig;
	}

	public void setTerritorioOrig(String territorioOrig) {
		this.territorioOrig = territorioOrig;
	}

	public String getCodiceIso() {
		return this.codiceIso;
	}

	public void setCodiceIso(String codiceIso) {
		this.codiceIso = codiceIso;
	}

	public Long getStatoCodifica() {
		return this.statoCodifica;
	}

	public void setStatoCodifica(Long statoCodifica) {
		this.statoCodifica = statoCodifica;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((codiceIso == null) ? 0 : codiceIso.hashCode());
		result = prime * result
				+ ((territorio == null) ? 0 : territorio.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof Territorio))
			return false;
		final Territorio other = (Territorio) obj;
		if (codiceIso == null) {
			if (other.getCodiceIso() != null)
				return false;
		} else if (!codiceIso.equals(other.getCodiceIso()))
			return false;
		if (territorio == null) {
			if (other.getTerritorio() != null)
				return false;
		} else if (!territorio.equals(other.getTerritorio()))
			return false;
		return true;
	}

	public String toString ()
	{
		return  id +":"+ territorio + ":"+codiceIso;
	}
}
