/*
 * AlmaRM Model - Java represenation of the model AlmaRM is built on.
 * Copyright (C) 2018  ALMA MATER STUDIORUM - Università di Bologna
 *
 * This file is part of AlmaRM Model.
 *
 * AlmaRM Model is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * AlmaRM Model is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with AlmaRM Model.  If not, see <https://www.gnu.org/licenses/>.
 */
package it.unibo.almarm.model.attori;

// Generated 19-feb-2008 15.24.59 by Hibernate Tools 3.2.0.CR1

import it.unibo.almarm.model.accordi.AccordoAttore;
import it.unibo.almarm.model.modalitapagamento.ModalitaDiPagamento;

import java.util.Comparator;
import java.util.HashSet;
import java.util.Set;

import com.thoughtworks.xstream.annotations.XStreamOmitField;

/**
 * Attore generated by hbm2java
 */
public class Attore implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	public enum tipoCodice
	{
		COD_PATRITA_IVA("PI"),
		COD_FISCALE("CF"),
		COD_NAZIONALE("CN");

		private String valore;
		tipoCodice(String v) {valore = v;}
		public String getValore() { return valore; }
	}

	
	protected boolean isInAnagrafica = true;
	
	protected Long id;
	@XStreamOmitField
	protected Set<RecapitoTelefonico> recapitoTelefonicos = new HashSet<RecapitoTelefonico>(0);
	@XStreamOmitField
	protected Set<AttoreIndirizzo> attoreIndirizzos = new HashSet<AttoreIndirizzo>(0);
	@XStreamOmitField
	protected Set<RecapitoEmail> recapitoEmails = new HashSet<RecapitoEmail>(0);
	@XStreamOmitField
	protected Set<ModalitaDiPagamento> modalitaDiPagamento = new HashSet<ModalitaDiPagamento>(0); 

	public Attore() {
	}

	public Attore(Long id) {
		this.id = id;
	}

	public Attore(Long id, Set<RecapitoTelefonico> recapitoTelefonicos,
			Set<AttoreIndirizzo> attoreIndirizzos,
			Set<RecapitoEmail> recapitoEmails) {
		this.id = id;
		this.recapitoTelefonicos = recapitoTelefonicos;
		this.attoreIndirizzos = attoreIndirizzos;
		this.recapitoEmails = recapitoEmails;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Set<RecapitoTelefonico> getRecapitoTelefonicos() {
		return this.recapitoTelefonicos;
	}

	public void setRecapitoTelefonicos(
			Set<RecapitoTelefonico> recapitoTelefonicos) {
		this.recapitoTelefonicos = recapitoTelefonicos;
	}

	public Set<AttoreIndirizzo> getAttoreIndirizzos() {
		return this.attoreIndirizzos;
	}

	public void setAttoreIndirizzos(Set<AttoreIndirizzo> attoreIndirizzos) {
		this.attoreIndirizzos = attoreIndirizzos;
	}

	public Set<RecapitoEmail> getRecapitoEmails() {
		return this.recapitoEmails;
	}

	public void setRecapitoEmails(Set<RecapitoEmail> recapitoEmails) {
		this.recapitoEmails = recapitoEmails;
	}

	public boolean isInAnagrafica() {
		return isInAnagrafica;
	}

	public void setInAnagrafica(boolean isInAnagrafica) {
		this.isInAnagrafica = isInAnagrafica;
	}

	public String getCodiceAttore()
	{
		return "";
	}
	
	public String getNomeAttore()
	{
		return "";
	}

	public Set<ModalitaDiPagamento> getModalitaDiPagamento() {
		return modalitaDiPagamento;
	}

	public void setModalitaDiPagamento(Set<ModalitaDiPagamento> modalitaDiPagamento) {
		this.modalitaDiPagamento = modalitaDiPagamento;
	}
	
	public boolean getIsStruttura()
	{
		return (this instanceof Struttura); 
	}
	
	public static class AttoreComparatorNomeAttore implements Comparator<Attore>
	{
		public int compare(Attore o1, Attore o2) {
			if (o1 == null && o2 == null)
				return 0;
			if (o1 == null || o1.getNomeAttore() == null)
				return 1;
			if (o2 == null || o2.getNomeAttore() == null)
				return -1;
			return o1.getNomeAttore().compareTo(o2.getNomeAttore());
		}
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof Attore))
			return false;
		Attore other = (Attore) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}
}
