/*
 * AlmaRM Model - Java represenation of the model AlmaRM is built on.
 * Copyright (C) 2018  ALMA MATER STUDIORUM - Università di Bologna
 *
 * This file is part of AlmaRM Model.
 *
 * AlmaRM Model is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * AlmaRM Model is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with AlmaRM Model.  If not, see <https://www.gnu.org/licenses/>.
 */
package it.unibo.almarm.model.attori;

// Generated 19-feb-2008 15.24.59 by Hibernate Tools 3.2.0.CR1

import it.unibo.almarm.model.luoghi.Localita;
import it.unibo.almarm.model.luoghi.Territorio;

/**
 * Indirizzo generated by hbm2java
 */
public class Indirizzo implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Long id;
	private String indirizzo;
	private String libero;
	private String cap;
	private Localita localita;
	private String localita_1;
	private Territorio territorio;
	private String territorio_1;
	private String frazione;

	public Indirizzo() {
	}

	public Indirizzo(Long id, Localita localita) {
		this.id = id;
		this.localita = localita;
	}

	public Indirizzo(Long id, String indirizzo, String libero, String cap,
			Localita localita, String frazione) {
		this.id = id;
		this.indirizzo = indirizzo;
		this.libero = libero;
		this.cap = cap;
		this.localita = localita;
		this.frazione = frazione;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getIndirizzo() {
		return this.indirizzo;
	}

	public void setIndirizzo(String indirizzo) {
		this.indirizzo = indirizzo;
	}

	public String getLibero() {
		return this.libero;
	}

	public void setLibero(String libero) {
		this.libero = libero;
	}

	public String getCap() {
		return this.cap;
	}

	public void setCap(String cap) {
		this.cap = cap;
	}

	public Localita getLocalita() {
		return this.localita;
	}

	public void setLocalita(Localita localita) {
		this.localita = localita;
	}

	public String getFrazione() {
		return this.frazione;
	}

	public void setFrazione(String frazione) {
		this.frazione = frazione;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((cap == null) ? 0 : cap.hashCode());
		result = prime * result
				+ ((frazione == null) ? 0 : frazione.hashCode());
		result = prime * result
				+ ((indirizzo == null) ? 0 : indirizzo.hashCode());
		result = prime * result + ((libero == null) ? 0 : libero.hashCode());
		result = prime * result
				+ ((localita == null) ? 0 : localita.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof Indirizzo))
			return false;
		final Indirizzo other = (Indirizzo) obj;
		if (cap == null) {
			if (other.getCap() != null)
				return false;
		} else if (!cap.equals(other.getCap()))
			return false;
		if (frazione == null) {
			if (other.getFrazione() != null)
				return false;
		} else if (!frazione.equals(other.getFrazione()))
			return false;
		if (indirizzo == null) {
			if (other.getIndirizzo() != null)
				return false;
		} else if (!indirizzo.equals(other.getIndirizzo()))
			return false;
		if (libero == null) {
			if (other.getLibero() != null)
				return false;
		} else if (!libero.equals(other.getLibero()))
			return false;
		if (localita == null) {
			if (other.getLocalita() != null)
				return false;
		} else if (!localita.equals(other.getLocalita()))
			return false;
		return true;
	}

	public String getLocalita_1() {
		return localita_1;
	}

	public void setLocalita_1(String localita_1) {
		this.localita_1 = localita_1;
	}

	public Territorio getTerritorio() {
		if ((territorio == null) && (localita != null))
			return localita.getTerritorio();
		return territorio;
	}

	public void setTerritorio(Territorio territorio) {
		this.territorio = territorio;
	}

	public String getTerritorio_1() {
		return territorio_1;
	}

	public void setTerritorio_1(String territorio_1) {
		this.territorio_1 = territorio_1;
	}

}
