/*
 * AlmaRM Model - Java represenation of the model AlmaRM is built on.
 * Copyright (C) 2018  ALMA MATER STUDIORUM - Università di Bologna
 *
 * This file is part of AlmaRM Model.
 *
 * AlmaRM Model is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * AlmaRM Model is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with AlmaRM Model.  If not, see <https://www.gnu.org/licenses/>.
 */
package it.unibo.almarm.model.attori;

import it.unibo.almarm.service.RecapitoTelefonicoManager.TipoTelefono;

// Generated 19-feb-2008 15.24.59 by Hibernate Tools 3.2.0.CR1

/**
 * RecapitoTelefonico generated by hbm2java
 */
public class RecapitoTelefonico implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Long id;
	private Attore attore;
	
	// Prefisso internazionale, con Giusti il 24/07/2008
	// si è convenuto di scrivere su database solo le cifre del prefisso
	// internazionale e non il carattere "+"
	private String prefissoInt; 
	
	private String telefono;
	private String nota;
	private String tipoVcard;
	private String tipo;
	private String tipoLuogo;
	private Long   privato;
	private Long   priorita;
	private String fonte;

	public RecapitoTelefonico() {
	}

	public RecapitoTelefonico(Long id) {
		this.id = id;
	}

	public RecapitoTelefonico(Long id, Attore attore, String prefissoInt,
			String telefono, String nota, String tipoVcard) {
		this.id = id;
		this.attore = attore;
		this.prefissoInt = prefissoInt;
		this.telefono = telefono;
		this.nota = nota;
		this.tipoVcard = tipoVcard;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Attore getAttore() {
		return this.attore;
	}

	public void setAttore(Attore attore) {
		this.attore = attore;
	}

	public String getPrefissoInt() {
		return this.prefissoInt;
	}

	public void setPrefissoInt(String prefissoInt) {
		this.prefissoInt = prefissoInt;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getNota() {
		return this.nota;
	}

	public void setNota(String nota) {
		this.nota = nota;
	}

	public String getTipoVcard() {
		return this.tipoVcard;
	}

	public void setTipoVcard(String tipoVcard) {
		this.tipoVcard = tipoVcard;
	}

	public String getTipo() {
		return tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getTipoLuogo() {
		return tipoLuogo;
	}

	public void setTipoLuogo(String tipoLuogo) {
		this.tipoLuogo = tipoLuogo;
	}

	public Long getPrivato() {
		return privato;
	}

	public void setPrivato(Long privato) {
		this.privato = privato;
	}

	public Long getPriorita() {
		return priorita;
	}

	public void setPriorita(Long priorita) {
		this.priorita = priorita;
	}

	public String getFonte() {
		return fonte;
	}

	public void setFonte(String fonte) {
		this.fonte = fonte;
	}

	public boolean isTelefonoEstero(){
		return TipoTelefono.CONTATTO_ESTERO.getValore().equals(this.getTipo());
	}
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((prefissoInt == null) ? 0 : prefissoInt.hashCode());
		result = prime * result
				+ ((telefono == null) ? 0 : telefono.hashCode());
		result = prime * result + ((tipo == null) ? 0 : tipo.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof RecapitoTelefonico))
			return false;
		final RecapitoTelefonico other = (RecapitoTelefonico) obj;
		if (prefissoInt == null) {
			if (other.getPrefissoInt() != null)
				return false;
		} else if (!prefissoInt.equals(other.getPrefissoInt()))
			return false;
		if (telefono == null) {
			if (other.getTelefono() != null)
				return false;
		} else if (!telefono.equals(other.getTelefono()))
			return false;
		if (tipo == null) {
			if (other.getTipo() != null)
				return false;
		} else if (!tipo.equals(other.getTipo()))
			return false;
		return true;
	}

	public String getStringaLeggibile()
	{
		return prefissoInt != null? prefissoInt + " " + telefono: telefono;
	}
}
