/*
 * AlmaRM Model - Java represenation of the model AlmaRM is built on.
 * Copyright (C) 2018  ALMA MATER STUDIORUM - Università di Bologna
 *
 * This file is part of AlmaRM Model.
 *
 * AlmaRM Model is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * AlmaRM Model is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with AlmaRM Model.  If not, see <https://www.gnu.org/licenses/>.
 */
package it.unibo.almarm.model.accordi;


// Generated 22-gen-2008 12.55.52 by Hibernate Tools 3.2.0.CR1

/**
 * TipoRuoloAccordo generated by hbm2java
 */
public class TipoRuoloAccordo implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	public static final Long CONTRAENTE = 1L;
	public static final Long ID_TIPO_RUOLO_RAPPRESENTANTE_LEGALE = 2L;
	public static final Long ID_TIPO_RUOLO_STRUTTURA = 5L;
	public static final Long ID_TIPO_RUOLO_BENEFICIARI = 6L;

	private Long id;
	private String descTipoRuolo;


	public TipoRuoloAccordo() {
		
	}
	
	public TipoRuoloAccordo(Long id) {
		this.id = id;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public boolean getIsRuoloContraente() {
		return (id.equals(CONTRAENTE));
	}
	
	public boolean getIsRuoloStruttura() {
		return (id.equals(ID_TIPO_RUOLO_STRUTTURA));
	}
	
	public boolean getIsRuoloRappresentanteLegale() {
		return (id.equals(ID_TIPO_RUOLO_RAPPRESENTANTE_LEGALE));
	}
	
	public String getDescTipoRuolo() {
		return this.descTipoRuolo;
	}

	public void setDescTipoRuolo(String descTipoRuolo) {
		this.descTipoRuolo = descTipoRuolo;
	}
	

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((descTipoRuolo == null) ? 0 : descTipoRuolo.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}



	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final TipoRuoloAccordo other = (TipoRuoloAccordo) obj;
		if (descTipoRuolo == null) {
			if (other.descTipoRuolo != null)
				return false;
		} else if (!descTipoRuolo.equals(other.descTipoRuolo))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	@Override
	public String toString() 
	{
		return id + ":" + descTipoRuolo;
	}

}
